# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  include SessionsHelper # despite the autogenerated line/comment above, this line includes
                         # the SessionsHelper in all views and controllers, the previous line
                         # will only include it in views
  
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  filter_parameter_logging :password
  
  # Execute code to detect mobile browser in every controller
  layout :detect_browser
  
  
  private
    # Code to detect mobile browsers so the
    # appropriate CSS files can be used
    # Special thanks to Jonathon Horsman
    # http://www.arctickiwi.com/blog/mobile-enable-your-ruby-on-rails-site-for-small-screens
    MOBILE_BROWSERS = ["android", "ipod", "opera mini", "blackberry", "palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", "windows ce; smartphone;","windows ce; iemobile", "up.browser","up.link","mmp","symbian","smartphone", "midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]

  def detect_browser
    agent = request.headers["HTTP_USER_AGENT"].downcase
    MOBILE_BROWSERS.each do |m|
      return "mobile_layout" if agent.match(m)
    end
    return "main_layout"
  end
    
end
